### ISSUE TITLE
Add tooltips with information about hovered nodes (Quick Info)

### ISSUE THREAD

**Issue by ashmind** [ashmind/mirrorsharp#10]

**Comment by SLaks** [comment]
The best way to implement this is to rewrite http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Extensions/ClassificationExtensions.cs,73 to generate HTML instead of WPF TextBlocks, then inject the subclasses of http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/QuickInfo/Providers/AbstractQuickInfoProvider.cs,5fa67eed62fb3e25,references.

But that would require working with lots of Roslyn internals, and stubbing parts of the WPF editors. 😞

**Comment by ashmind** [comment]
@SLaks I think fetching on hover is OK, I send a two-byte server request for each char you type anyways (that's how autocompletion works atm), hover is minor compared to that.

**Comment by ashmind** [comment]
It's a single WebSocket connection anyways.

**Comment by SLaks** [comment]
OTOH, hover can happen much more frequently than typing if you rapidly move the mouse over a complex document.

You might want to only send the request if the mouse stays (over the symbol|within a 20px area) for ~150ms, like most tooltips.  (HTML has no native event for that)

**Comment by ashmind** [comment]
@SLaks Yep I plan to do a delayed hover -- I think VS delays it as well.

**Comment by ashmind** [comment]
@SLaks Spent a lot of time on this, but it seems there is just no good way to use `IQuickInfoProvider` until they make it public. Reflection doesn't get me far enough since the code depends on Visual Studio types. I can't easily rewrite the assembly because of `InternalsVisibleTo` and strong names. I tried extracting the code from Roslyn using Roslyn and rewriting the dependencies, but there is just too many dependencies -- I end up having a copy of half of Roslyn -- which is also confusing for branch tracking since code won't match the branch.

It's probably solvable, but requires maybe another week, so I'll give up for now -- too much effort for a tooltip.

**Comment by ashmind** [comment]
This is now implemented. Note that in SharpLab you can only see it on Default (and x64).
Branch builds use an older version, as a lot of branches does not have QuickInfo API yet and I have to use same version for all branches.
