### ISSUE TITLE
What is SlowUpdate?

### ISSUE THREAD

**Issue by FortuneN** [ashmind/mirrorsharp#108]

**Comment by ashmind** [comment]
This is a periodic compile/check operation that updates the syntax tree and reports any errors. It's called "Slow" because it happens on (client-side) timer and does not block user, which allows it to care less about performance (not that I control Roslyn compilation performance either way).

On client-side this is triggered by the `lint` operation in CodeMirror (which happens every X milliseconds, don't remember specific value).

**Comment by ashmind** [comment]
Closing as answered, but I can reopen if you have further questions.
