### ISSUE TITLE
[Question] use with legacy .net 4.7.2

### ISSUE THREAD

**Issue by albertoVieiraNeto** [ashmind/mirrorsharp#116]
Hi.

Is there anyway to use mirrorsharp with a existing API built using the default API template for .net 4.7.2 (full framework) ?

global.asax ->GlobalConfiguration.Configure

**Comment by ashmind** [comment]
Hmm, I don't have a server example for that use case at the moment. I would expect that you can make it work by either:
1. Using `Owin` startup instead of `GlobalConfiguration.Configure` and using `MirrorSharp.Owin`
2. Managing socket manually using something like https://stackoverflow.com/a/25672569/39068. I wouldn't recommend this as a lot of MirrorSharp parts around this are internal -- I can give some way to work with that, but 1 is preferable.

**Comment by albertoVieiraNeto** [comment]
thanks, that's what i thought i posted just to make sure i was not missing anything. awsome work btw, this project is amazing.
