### ISSUE TITLE
When updating MirrorSharp breaks

### ISSUE THREAD

**Issue by Sicos1977** [ashmind/mirrorsharp#219]
When updating to version 4.6 on one of the component below MirrorSharp breaks. I don't get any error but the communication from codemirror fails and complains about websocket state 3

![image](https://github.com/ashmind/mirrorsharp/assets/6692947/df00d576-7018-4b64-af14-c113026a6351)

**Comment by Sicos1977** [comment]
Thanks for fixing....

Also just another question. Is there a timeline when an official release will be there for codemirror 6? Is see that you have added some very nice new features like code completion that are not in mirrorsharp in combination with codemirror 5.

**Comment by ashmind** [comment]
The fix for this issue is included in https://www.nuget.org/packages/MirrorSharp.Common/3.0.6 (just released).

As for CodeMirror 6, there is no specific timeline -- it should be mostly stable already but there are still a bit of edge cases to investigate, and I wasn't actively looking at them for a while.

There should be no completely new features though, just changes to how features are presented.
Code completion should already work in CM5 (though CM6 might be more reliable in mobile browsers).

**Comment by Sicos1977** [comment]
> The fix for this issue is included in https://www.nuget.org/packages/MirrorSharp.Common/3.0.6 (just released).
> 
> As for CodeMirror 6, there is no specific timeline -- it should be mostly stable already but there are still a bit of edge cases to investigate, and I wasn't actively looking at them for a while.
> 
> There should be no completely new features though, just changes to how features are presented. Code completion should already work in CM5 (though CM6 might be more reliable in mobile browsers).

What I mean with code completion is functionality like this

![image](https://github.com/ashmind/mirrorsharp/assets/6692947/54418d2a-e214-40c9-9e30-90d7b3b8d145)

and

![image](https://github.com/ashmind/mirrorsharp/assets/6692947/30bb0f66-49f7-4b36-8509-58df60d0012e)

I never have seen that in the current implementation I have with codemirror 5
